[[Libxc_GPU]]
arch = "aarch64"
cuda = "12.4"
cuda_platform = "sbsa"
git-tree-sha1 = "eeb9e59c564aca4476d180c6f58e8cf13b15055d"
lazy = true
libc = "glibc"
os = "linux"

    [[Libxc_GPU.download]]
    sha256 = "18f30d05d739de56dd1db7fe085ba85a077ddb24dd1127042daa28558286299f"
    url = "https://github.com/abussy/Libxc_GPU_jll.jl/releases/download/Libxc_GPU-v7.0.0+0/Libxc_GPU.v7.0.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.4.tar.gz"
